processed_uri: ~/some/transaction/db

# Extraction step of the ETL pipeline
extract:
  type: csv
  args:
    glob_pattern: ~/some/directory/data/chase/*.csv
    csv_options:
      sep: ","

# List of transformations to apply
transforms:
    # Add the account column
    - step: AddColumn
      args:
        literal: Liabilities:US:Chase:0001
        outcol: amount
  
    # Generate a currency column
    - step: AddColumn
      args:
        literal: USD
        outcol: cost_currency

    # Remove non-alphanumeric characters from the narrations
    - step: StringCleaner
      args:
        col: Description
        outcol: narration
        regex: "[^a-zA-Z0-9 ]"
        replacement: 

    # Convert dates to datetime object
    - step: DatetimeTransform
      args:
        col: Transaction Date
        outcol: transaction_date
        fmt: "%m/%d/%Y"
    - step: DatetimeTransform
      args:
        col: Post Date
        outcol: posting_date
        fmt: "%m/%d/%Y"

    # Rename columns to fit the schema
    - step: RenameCol
      args:
        in: Category
        out: category
    - step: RenameCol
      args:
        in: Amount
        out: cost_amount

